TT = ['bike', 'car', 'cargobike', 'van', 'walk', 'motorbike', 'motorbikexl']
ALL = 'all'
DO, PU = 'do', 'pu'
JOB_TYPES = [DO, PU]
KDE, HIST = 'kde', 'hist'
PLOT_TYPES = [KDE, HIST]
EARLINESS_ARIVALL = 'almost_picking_at_vs_pickup_at'
TIME_WINDOW_JOB_TYPE = {PU: 15, DO: 30}
BW_METHOD = 0.75
HIST_ALPHA = 0.5
BINS = 100
BINS_CUMULATIVE = 1000
XLIM = (-15, 45)
FIGSIZE = (20, 20)